# Generated by Django 6.1 on 2026-09-01 14:43

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('domain', models.TextField(help_text='Comma-separated list of allowed URLs including protocol (e.g. https://example.com,http://app.example.org).', validators=[clients.validators.validate_domains], verbose_name='allowed domains')),
                ('secret', models.CharField(blank=True, max_length=255, unique=True, verbose_name='secret token')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, related_name='clients', to='auth.group', verbose_name='groups')),
                ('permissions', models.ManyToManyField(blank=True, related_name='clients', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
