# Generated by Django 6.1 on 2026-08-19 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('template_url', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
                ('regex', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('identifier',),
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network_instances', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='profiles.socialnetworkconfig')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='socialnetworkconfig',
            name='variables',
            field=models.ManyToManyField(related_name='configs', to='profiles.variable'),
        ),
        migrations.CreateModel(
            name='VariableInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('social_network_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variable_instances', to='profiles.socialnetworkinstance')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='profiles.variable')),
            ],
            options={
                'ordering': ('variable__identifier',),
            },
        ),
    ]
