# Generated by Django 6.1 on 2026-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='identifier',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
