# Generated by OpenCode

from django.db import migrations


def create_onboarding_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    PublicProfile = apps.get_model("profiles", "PublicProfile")

    content_type = ContentType.objects.get_for_model(PublicProfile)
    add_permission, _ = Permission.objects.get_or_create(
        codename="add_publicprofile",
        content_type=content_type,
        defaults={"name": "Can add public profile"},
    )
    group, _ = Group.objects.get_or_create(name="Public Profile Onboarding")
    group.permissions.add(add_permission)


def remove_onboarding_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Public Profile Onboarding").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_publicprofile"),
    ]

    operations = [
        migrations.RunPython(create_onboarding_group, remove_onboarding_group),
    ]
